### PR TITLE
Add systemd script (unit definition).

### PR DESCRIPTION
**Pull request by cfallin**
Greetings, @nixprime!

I found Switchboard by way of idle Github browsing and it has actually been pretty useful to me (thanks!). I run Arch at home so I had to write a systemd unit definition to start it at boot. I took the liberty of some `README.md` reorganization as well when I added instructions for systemd-based systems.

### CODE REVIEW

**Comment by cfallin** [comment]
Good to know! Updated, PTAL.

(Followup commit for codereview updates as per PR etiquette I was accustomed to, but can squash if desired.)

**Comment by nixprime** [comment]
I'd prefer if you squashed. Thanks!

**Comment by cfallin** [comment]
Sure thing. Done, PTAL.

**Comment by nixprime** [comment]
... Github deletes comments from previous versions of a change after a rebase? TIL. Anyway, thanks again!

Edit: Ok, now I have no idea what's going on. Hmm. Oh well.

**Comment by cfallin** [comment]
Ah, yes, IIRC your original comment was a commit comment, so disappeared with the old commit. I think diff comments stick around even after history rewrites, though? In any case, thanks!

**Pull request merged**
